### ISSUE TITLE
explain difference to linker symbol renaming

### ISSUE THREAD

**Issue by matu3ba** [ThePhD/transparent-aliases#1]
As I understand it, you suggest to conditionally select (function) symbols, which is can be seen as a linker task.
Although it feels necessary due to inability for breaking changes of the c committee.

Why do you believe is it better to do at the language level, which will likely be rejected by commitee?
My idea to solve this without any reliance on commitee would be to have tooling for:
1. abi specification format inclusive versioning, 2. abi tool, 3. proper linker language instead of hacky linker scripts
Inspiration for 1+2 can be taken from
https://github.com/microsoft/win32metadata and https://github.com/ziglang/glibc-abi-tool

**Comment by ThePhD** [comment]
How do you use these tools across all implementations of the C language?

**Comment by matu3ba** [comment]
excellent question. I am trying to sketch an ideal solution for simplicity.
- To get 2 one would obtain all release commits of compiler implementations wrt each standard and extract the symbols as specified in the c standard.
- To get 1 in a nice way, it would be required to compare each symbol semantically against the corresponding other one, if existing.
- Point 3 requires to hand-code the logic for selection, which will most likely be provided by each compiler vendor. I dont know how complex such a linker logic would be and the state of art on linker scripts is not great https://mcyoung.xyz/2021/06/01/linker-script/ with some hope https://github.com/ziglang/zig/issues/3206 https://github.com/rui314/mold/issues/4
More realistically 3 would be done per compiler and the data for 1+2 merged.

If I now think more about it, I think your suggestion is simpler to implement which fits more to the way of C.
Personally I think that providing stuff like `alias` without proper symbol introspection has the same very significant downsides of shell scripting, as authors can not automatically check if changes broke their old code.

**Comment by matu3ba** [comment]
Implementation too complex and state of art on linker is insufficient.

**Comment by ThePhD** [comment]
I appreciate that there are more complex answers, but yes. A lot of what you're advocating would be unneeded / redundant on simpler implementations, where C / POSIX global table is the only "shared library" you can have, and everything else is just a guest program. I would like to avoid needing to tap the entirety of the world of linkers, which itself has not standardized object file formats or similar across even the major 3 OSes for even a single architecture (e.g., x86_64), just to solve the symbol indirection problem.
